name: Entity Police
main: me.potatofarms.entitypolice.EntityPolice
description: control them entities!
version: 0.2

commands:
   entitypolice:
      description: main command.
      usage: /<command> <count:remove> <mob> <(optional) world>
   ep:
      description: main command.
      usage: /<command> <count:remove> <mob> <(optional) world>
permissions:
    entitypolice.*:
        description: Gives access to all entitypolice commands.
        children:
            entitypolice.help: true
            entitypolice.count: true
            entitypolice.remove: true
    entitypolice.help:
        description: Gives access to the help command.
        default: op
    entitypolice.count:
        description: Gives access to the count command.
        default: op
    entitypolice.remove:
        description: Gives access to the remove command.
        default: op